In [5]:
import re
import datetime

In [14]:
txt = '00sd00_4908.jpg'
'.'.join(re.split('\_[\d]*\.', txt))

'00sd00.jpg'

In [8]:
a = datetime.datetime.now()

In [11]:
b = datetime.datetime.now() - a

In [12]:
str(b)

'0:00:22.516167'

In [1]:
import numpy as np

In [17]:
arr = np.array([[0,1,1,0],[0,1,0,0], [0,0,1,0]] )
arr

array([[0, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [18]:
arr.T

array([[0, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [19]:
arr.T.flatten()

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [20]:
def rle_encoding(x):
    '''
    x: numpy array of shape (height, width), 1 - mask, 0 - background
    Returns run length as list
    '''
    dots = np.where(x.T.flatten()==1)[0] # .T sets Fortran order down-then-right
    run_lengths = []
    prev = -2
    for b in dots:
        if (b>prev+1): run_lengths.extend((b+1, 0))
        run_lengths[-1] += 1
        prev = b
    return run_lengths
b = rle_encoding(arr)

In [21]:
conv = lambda l: ' '.join(map(str, l)) # list -> string

In [22]:
conv(b)

'4 2 7 1 9 1'